language: node_js
node_js:
- '6'

services:
 - mongodb

before_script:
  - mongo opengramtest --eval "db.dropDatabase()"

before_install:
  npm install --only=dev
install:
  npm install

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "kHygHNd469s+H4JbpnNTWFmP/4fQaaLj6yigLRb7cTfoeVexnNQkbDzUTbDKrSQX2MkLZHUuFnoalFHhtwBLRH0k7xBBKe26GDSO36vMwtoNsj46YhIIxfO03gObGbO599l+g2B7lHpnNG8+7zya6XEy3FouZ55wWzsD6gnWiKCZvLeyabZ/BPelEifvgyyyLgp9KtUz0sQHSmCKsq62KNLLohkd1rvRP7Bgr6v8m1MsUhx5WhamBbOSIPVGOhzi9Ng7VHH69LBZVtCYADLYp/rvqYTqmm3EwkTMuS2xhCpug5GTkP4Q5fUQyhBE5gUxJ2Ve4B0ncR2HS/VH8M7ukJnsiMnwkIyrD1AAQRqpdN9/40jiKV85K2a1eL5FfFUB7VQK4hIeMjHGNxCWhmREcfLDsyhDUHC0//c0mHZnFLYyfxyZU79SdaOJwh0nwGXirp+xHwEZMo/5KHpW+Nj+E4mzSMMs20CFXUE2oQknl2MuVVZhodiYS6/QZU+7AJvrrDWMZAsSNLwQi5LnmNHNYgOQ9qjIQHx+CZRUEmE6bWVNFyaC3Sk/ZlWCbT2WBp7UkH7FQRJNteHkAWYJ+fyQDD5HzjqBNWhA7zF1GPBU2W3OlejIKnSbeu9//lma1nNpcIsbqRsdsH5a5YfgzflRUfWUE6sz8N/QuFwAuW1Oz1o="
