language: node_js
node_js:
  - "6"

deploy:
  provider: heroku
  api_key:
    secure: "qEFKQif3n8sVvjd8s6vWR75olDTrijjd9E+iaMS2TE9QiXjxIZX2s3nG8Ru5MBe41cUsyOYHw9QR2Syn35YFLRTyRTBEIjnN3vAzAX3xc4hEthgD7l4lyB+AVlr2JwgcASDqHCQfY6MJ/GHe5Vo/L/RQPl3jODmkbjai3FUt1UkbkBnExaO0zo/Yh4zgfAt7rkKzVKx71AWbnNdLbehGYM74Uknbqokl5WMPk1/s4AQvuDnJR+wN++g09/HnndQwKahAYhUTV+l+3YcwRW3WEvcsBKhbp7rddNyxcSBnspndNXWzapp6xeqKZDthzeZ7RB+653EltXy4nWIiKBw+Y+59lUgRLBWzg/3pOgL7QquZiqVYMMBrVmvvlit/eUswELLEk7ji3p7t/0hLpVOy9RzS8sN7LLxD5pqeh1YK/9gYIR4QMvFbQgadhh4ppwuPSGVtQQ4ZOaSZ6Y484DZU/RcqQy7Vy1aryM9FgtdzlgXPfneG8Im3hz3OO3iwkEknBzt72YX8z2siaIgH0LOgylSOnPqpc/GxOybT8+/1SIIhxysyA736HbOmU74Aue6TLC/nKD0JExo2xw5uzWUblPVAYqQBo79yibbDMDm9pd42Sr1xXmyjA/BmUkbhU1Se2x+hJouFCc2Imtu6xjqbHe9entJKXqa2sgPgwgVLNew="
